x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  evm:
    build:
      context: ./evm
      dockerfile: Dockerfile
      args:
        - EVM_NODE_TAG=${EVM_NODE_TAG}
    image: evm:${EVM_NODE_TAG}
    pull_policy: never
    restart: unless-stopped
    environment:
      - NETWORK=${NETWORK}
      - EVM_ONLY=${EVM_ONLY:-true}
      - ROLLUP_NODE_URL=${ROLLUP_NODE_URL:-http://rollup:8932}
    entrypoint: docker-entrypoint.sh
    volumes:
      - ./evm/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - evm_data:/data
    <<: *logging
    labels:
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST:-etherlink}.service=${RPC_HOST:-etherlink}
      - traefik.http.routers.${RPC_HOST:-etherlink}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-etherlink}.rule=Host(`${RPC_HOST:-etherlink}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-etherlink}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST:-etherlink}lb.service=${RPC_HOST:-etherlink}
      - traefik.http.routers.${RPC_HOST:-etherlink}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-etherlink}lb.rule=Host(`${RPC_LB:-etherlink-lb}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-etherlink}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST:-etherlink}.loadbalancer.server.port=8545

volumes:
  evm_data:
