x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  rollup:
    build:
      context: ./rollup
      dockerfile: Dockerfile
      args:
        - ROLLUP_NODE_TAG=${ROLLUP_NODE_TAG}
    image: rollup:${ROLLUP_NODE_TAG}
    pull_policy: never
    restart: unless-stopped
    environment:
      - NETWORK=${NETWORK}
      - ROLLUP_SNAPSHOT=${ROLLUP_SNAPSHOT:-}
    entrypoint: docker-entrypoint.sh
    volumes:
      - ./rollup/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - rollup_data:/data
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=6060
      - metrics.network=${NETWORK:-}

volumes:
  rollup_data:
